compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: config_mg/deepspeed_zero2.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
main_process_port: 1110
main_training_function: main
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
